Repository projectmesa/mesa, pull requests merged in 2018-05, with the labels that each got.

#519 fix minor flake8 issues
  mesa/batchrunner.py
Labels: Sprints!

#530 Add a code of conduct
  CODE_OF_CONDUCT.md
Labels: Sprints!

#535 Fixes Flake8 issues in PR528.
  setup.py
  tests/test_lifespan.py
Labels: 4 - Ready to Merge, Sprints!

#539 Fixes #499 grid size issue.
  examples/epstein_civil_violence/civil_violence/server.py
Labels: 4 - Ready to Merge, Sprints!, easy task!!!
