Repository projectmesa/mesa, pull requests merged in 2018-03, with the labels that each got.

#479 Merge packages to mesa_packages branch
  docs/index.rst
  docs/packages/Package Development/package development main.rst
  docs/packages/Package Development/package template.rst
  docs/packages/User Guide/user guide main.rst
  docs/packages/package_main.rst
Labels: 4 - Accept

#453 [Minor] Fixing date on release.
  HISTORY.rst
Labels: 4 - Accept, easy task!!!

#486 Batchrunner fixes: properly initialize models with correct parameters during subsequent runs.
  mesa/batchrunner.py
Labels: 4 - Accept

#489 [BUGFIX] Updating version of tornado b/c old version breaks jupyter.
  requirements.txt
Labels: easy task!!!
