Repository projectmesa/mesa, pull requests merged in 2018-10, with the labels that each got.

#572 Adding model random number generator with __new__
  docs/best-practices.rst
  docs/overview.rst
  docs/tutorials/intro_tutorial.ipynb
  docs/tutorials/intro_tutorial.rst
  examples/Schelling/model.py
  examples/bank_reserves/bank_reserves/agents.py
  examples/bank_reserves/bank_reserves/model.py
  examples/bank_reserves/bank_reserves/random_walk.py
  examples/bank_reserves/batch_run.py
  examples/boid-flockers/boid_flockers/model.py
  examples/boltzmann_wealth_model/boltzmann_wealth_model/model.py
  examples/boltzmann_wealth_model_network/boltzmann_wealth_model_network/model.py
  examples/color_patches/color_patches/model.py
  examples/conways_game_of_life/conways_game_of_life/model.py
  examples/epstein_civil_violence/epstein_civil_violence/agent.py
  examples/epstein_civil_violence/epstein_civil_violence/model.py
  examples/forest_fire/Forest Fire Model.ipynb
  examples/forest_fire/forest_fire/model.py
  examples/pd_grid/analysis.ipynb
  examples/pd_grid/pd_grid/agent.py
  examples/pd_grid/pd_grid/model.py
  examples/shape_example/shape_example/model.py
  examples/shape_example/shape_example/server.py
  examples/sugarscape_cg/sugarscape_cg/agents.py
  examples/sugarscape_cg/sugarscape_cg/model.py
  examples/sugarscape_cg/sugarscape_cg/schedule.py
  examples/virus_on_network/virus_on_network/model.py
  examples/wolf_sheep/wolf_sheep/agents.py
  examples/wolf_sheep/wolf_sheep/model.py
  examples/wolf_sheep/wolf_sheep/random_walk.py
  examples/wolf_sheep/wolf_sheep/schedule.py
  examples/wolf_sheep/wolf_sheep/test_random_walk.py
  mesa/agent.py
  mesa/cookiecutter-mesa/{{cookiecutter.snake}}/{{cookiecutter.snake}}/model.py
  mesa/model.py
  mesa/space.py
  mesa/time.py
  tests/test_grid.py
  tests/test_time.py
Labels: 4 - Accept, help wanted

#584 agents can be removed and added during Scheduler.step()
  mesa/time.py
Labels: 4 - Accept

#465 Added mouse interactionHandler to close #457, fixed hexgrid drawLines
  mesa/visualization/modules/CanvasGridVisualization.py
  mesa/visualization/modules/HexGridVisualization.py
  mesa/visualization/templates/css/visualization.css
  mesa/visualization/templates/js/CanvasHexModule.js
  mesa/visualization/templates/js/CanvasModule.js
  mesa/visualization/templates/js/GridDraw.js
  mesa/visualization/templates/js/HexDraw.js
  mesa/visualization/templates/js/InteractionHandler.js
Labels: 3 - Working, Sprints!, front end
