Repository projectmesa/mesa, pull requests merged in 2019-02, with the labels that each got.

#635 Example updates
  examples/boid-flockers/requirements.txt
  examples/epstein_civil_violence/requirements.txt
  examples/forest_fire/requirements.txt
  examples/pd_grid/requirements.txt
  examples/sugarscape_cg/requirements.txt
Labels: easy task!!!

#594 Add Pie Chart visualization and include in forest_fire example (Issue #490)
  examples/charts/Readme.md
  examples/charts/charts/agents.py
  examples/charts/charts/model.py
  examples/charts/charts/random_walk.py
  examples/charts/charts/server.py
  examples/charts/requirements.txt
  examples/charts/run.py
  examples/forest_fire/forest_fire/server.py
  mesa/visualization/modules/BarChartVisualization.py
  mesa/visualization/modules/PieChartVisualization.py
  mesa/visualization/modules/__init__.py
  mesa/visualization/templates/js/BarChartModule.js
  mesa/visualization/templates/js/PieChartModule.js
Labels: 4 - Accept

#634 Updating the docs for the new version of Chart.js
  docs/tutorials/adv_tutorial.rst
Labels: 4 - Ready to Merge
