Repository projectmesa/mesa, pull requests merged in 2019-05, with the labels that each got.

#666 V0.8.6 release
  HISTORY.rst
  mesa/__init__.py
Labels: 4 - Accept

#669 Issue #668
  docs/Useful-snippets/snippets.rst
Labels: pycon 2019

#671 update tutorial to point to correct repo location
  docs/tutorials/intro_tutorial.rst
Labels: pycon 2019

#672 updating index.rst
  docs/best-practices.rst
  docs/index.rst
Labels: pycon 2019

#674 sphinx set up
  docs/index.rst
  docs/mesa.rst
  docs/mesa.visualization.modules.rst
  docs/mesa.visualization.rst
  docs/tutorials/adv_tutorial.rst
  docs/tutorials/intro_tutorial.rst
  docs/tutorials/intro_tutorial_files/intro_tutorial_18_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_20_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_31_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_37_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_41_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_43_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_51_1.png
Labels: pycon 2019

#651 Batch runner params
  mesa/batchrunner.py
  tests/test_batchrunner.py
Labels: 4 - Accept, pycon 2019

#678 Add pipenv support for mesa
  Pipfile
  Pipfile.lock
Labels: pycon 2019

#682 Clarify runserver snippet in index.rst
  docs/index.rst
Labels: pycon 2019

#686 Fixes code blocks that weren't showing up in the tutorial
  docs/tutorials/adv_tutorial.rst
  docs/tutorials/intro_tutorial.rst
Labels: pycon 2019

#691 Resources #651 in docs branch
  mesa/batchrunner.py
  tests/test_batchrunner.py
Labels: 4 - Ready to Merge, pycon 2019

#684 Bulk merge of docs from 'docs' to 'master'
  docs/best-practices.rst
  docs/index.rst
  docs/mesa.rst
  docs/mesa.visualization.modules.rst
  docs/mesa.visualization.rst
  docs/tutorials/adv_tutorial.rst
  docs/tutorials/intro_tutorial.rst
  docs/tutorials/intro_tutorial_files/intro_tutorial_18_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_20_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_31_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_37_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_41_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_43_1.png
  docs/tutorials/intro_tutorial_files/intro_tutorial_51_1.png
  docs/useful-snippets/snippets.rst
Labels: 4 - Ready to Merge
