Repository projectmesa/mesa, pull requests merged in 2024-08, with the labels that each got.

#2195 devs/eventlist: Add str and repr methods to print EventList
  mesa/experimental/devs/eventlist.py
Labels: experimental, enhancement

#2198 chore: Remove unused direct dependency
  pyproject.toml
Labels: ignore-for-release

#2206 docs/conf.py: Use modern `intersphinx_mapping` format
  docs/conf.py
Labels: docs, ci

#2203 docs: Update Readme and tutorials to mention Mesa 3.0 pre-releases
  README.md
  docs/tutorials/intro_tutorial.ipynb
  docs/tutorials/visualization_tutorial.ipynb
Labels: docs

#2219 Allow AgentSet.do() to take Callable function
  mesa/agent.py
  tests/test_agent.py
Labels: breaking, enhancement

#2225 Change warning when setting model.agents to error
  mesa/model.py
Labels: breaking

#2173 CI: Add test job for Python 3.13
  .github/workflows/build_lint.yml
Labels: ci

#2237 Split AgentSet into map and do to seperate return types
  mesa/agent.py
  tests/test_agent.py
Labels: enhancement

#2220 Add AgentSet.groupby
  mesa/agent.py
  tests/test_agent.py
Labels: feature

#2217 Add pull request templates
  .github/PULL_REQUEST_TEMPLATE/bug.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
Labels: maintenance

#2252 benchmarks: Add BoltzmannWealth model
  benchmarks/BoltzmannWealth/__init__.py
  benchmarks/BoltzmannWealth/boltzmann_wealth.py
  benchmarks/configurations.py
  benchmarks/global_benchmark.py
Labels: testing, ci

#2254 AgentSet: Add `set` method
  mesa/agent.py
  tests/test_agent.py
Labels: feature

#2251 Performance enhancements for Model.agents
  mesa/agent.py
  mesa/model.py
Labels: Performance, breaking

#2253 AgentSet: Allow selecting a fraction of agents in the AgentSet
  mesa/agent.py
  tests/test_agent.py
Labels: enhancement, deprecation

#2084 Voronoi Tesselation based Discrete Space
  mesa/experimental/cell_space/__init__.py
  mesa/experimental/cell_space/voronoi.py
  mesa/visualization/components/matplotlib.py
  tests/test_cell_space.py
  tests/test_solara_viz.py
Labels: feature, experimental

#2258 Contribution: Add "I have no idea where to start" section
  CONTRIBUTING.md
Labels: docs

#2256 Readme: Add direct links to Visualization Tutorial and dev docs
  README.md
Labels: docs, ignore-for-release

#2257 Write initial Mesa Migration guide
  docs/index.md
  docs/migration_guide.md
Labels: docs
