Repository projectmesa/mesa, pull requests merged in 2024-02, with the labels that each got.

#2015 feat: Let mesa runserver detect server.py as fallback
  mesa/main.py
Labels: feature

#2040 ci: Move codespell to pre-commit
  .github/workflows/codespell.yml
  .pre-commit-config.yaml
Labels: ci

#2035 docs: Convert api/*.rst -> api/*.md via rst2myst
  docs/apis/api_main.md
  docs/apis/api_main.rst
  docs/apis/batchrunner.md
  docs/apis/datacollection.md
  docs/apis/init.md
  docs/apis/space.md
  docs/apis/space.rst
  docs/apis/time.md
  docs/apis/visualization.md
Labels: docs

#2037 docs: Rewrite howto.md using ChatGPT for clarity and conciseness
  docs/howto.md
Labels: docs

#2044 new feature: AgentSet.get can retrieve one or more then one attribute
  mesa/agent.py
  tests/test_agent.py
Labels: feature

#2052 Update CODE_OF_CONDUCT.md to version 2+ of contrib convenant
  CODE_OF_CONDUCT.md
Labels: enhancement

#1994 Add cell-centric discrete spaces (experimental)
  benchmarks/Schelling/schelling.py
  benchmarks/WolfSheep/wolf_sheep.py
  mesa/experimental/__init__.py
  mesa/experimental/cell_space/__init__.py
  mesa/experimental/cell_space/cell.py
  mesa/experimental/cell_space/cell_agent.py
  mesa/experimental/cell_space/cell_collection.py
  mesa/experimental/cell_space/discrete_space.py
  mesa/experimental/cell_space/grid.py
  mesa/experimental/cell_space/network.py
  tests/test_cell_space.py
Labels: feature, experimental

#2065 Stabilize AgentSet
  mesa/agent.py
  mesa/model.py
Labels: feature
