Repository projectmesa/mesa, pull requests merged in 2024-12, with the labels that each got.

#2523 added empty iterable checks and updated tests
  mesa/batchrunner.py
  tests/test_batch_run.py
Labels: maintenance

#2351 Add `create_agent` factory method to Agent
  mesa/agent.py
  tests/test_agent.py
Labels: discuss, feature

#2512 Add full support for property layers to cell spaces
  mesa/experimental/cell_space/__init__.py
  mesa/experimental/cell_space/cell.py
  mesa/experimental/cell_space/discrete_space.py
  mesa/experimental/cell_space/grid.py
  mesa/experimental/cell_space/property_layer.py
  mesa/visualization/mpl_space_drawing.py
  tests/test_cell_space.py
  tests/test_components_matplotlib.py
Labels: feature

#2532 Add module-level docstring to experimental features
  .codespellignore
  mesa/experimental/__init__.py
  mesa/experimental/cell_space/__init__.py
  mesa/experimental/cell_space/cell.py
  mesa/experimental/cell_space/cell_agent.py
  mesa/experimental/cell_space/cell_collection.py
  mesa/experimental/cell_space/discrete_space.py
  mesa/experimental/cell_space/grid.py
  mesa/experimental/cell_space/network.py
  mesa/experimental/cell_space/property_layer.py
  mesa/experimental/cell_space/voronoi.py
  mesa/experimental/devs/__init__.py
  mesa/experimental/devs/eventlist.py
  mesa/experimental/devs/simulator.py
  mesa/experimental/mesa_signals/__init__.py
  mesa/experimental/mesa_signals/mesa_signal.py
  mesa/experimental/mesa_signals/observable_collections.py
  mesa/experimental/mesa_signals/signals_util.py
Labels: docs

#2531 Update release notes and version for 3.1.0
  HISTORY.md
  mesa/__init__.py
Labels: ignore-for-release

#2540 Add Interactive Play Interval Control to Mesa Visualization
  mesa/visualization/solara_viz.py
Labels: visualisation

#2543 Wolf-sheep to use `create_agent`
  mesa/examples/advanced/wolf_sheep/agents.py
  mesa/examples/advanced/wolf_sheep/model.py
Labels: example

#2518 Fix: Schelling Model Neighbor Similarity Calculation
  mesa/examples/basic/schelling/agents.py
  mesa/examples/basic/schelling/app.py
Labels: example

#2541 Update tutorials to use `create_agents` and `rng.integers`
  docs/tutorials/MoneyModel.py
  docs/tutorials/intro_tutorial.ipynb
Labels: docs

#2550 Update release notes and version for 3.1.1
  HISTORY.md
  mesa/__init__.py
Labels: ignore-for-release

#2503 examples/wolf_sheep: Don't allow dumb moves
  mesa/examples/advanced/wolf_sheep/agents.py
Labels: example

#2520 Added homophily ratio in basic schelling example
  benchmarks/configurations.py
  mesa/examples/basic/schelling/app.py
  mesa/examples/basic/schelling/model.py
Labels: example

#2583 Corrected a few errors in Intro tutorial
  docs/tutorials/intro_tutorial.ipynb
Labels: docs
