Repository projectmesa/mesa, pull requests merged in 2024-09, with the labels that each got.

#2267 Model: Replace `get_agents_of_type` method with `agents_by_type` property
  benchmarks/WolfSheep/wolf_sheep.py
  mesa/experimental/devs/examples/wolf_sheep.py
  mesa/model.py
  tests/test_model.py
  tests/test_time.py
Labels: enhancement, deprecation

#2266 AgentSet: Add `agg` method
  mesa/agent.py
  tests/test_agent.py
Labels: feature

#2272 docs: Fix Visualization Tutorial (2.x branch)
  docs/tutorials/visualization_tutorial.ipynb
Labels: docs, maintenance, ignore-for-release

#2271 docs: Fix Visualization Tutorial (main branch)
  docs/tutorials/visualization_tutorial.ipynb
Labels: docs, maintenance

#2274 Docs: Fix broken relative links by removing `.html` suffix
  docs/index.md
  docs/overview.md
Labels: docs

#2260 track unique_id automatically
  benchmarks/BoltzmannWealth/boltzmann_wealth.py
  benchmarks/Flocking/flocking.py
  benchmarks/Schelling/schelling.py
  benchmarks/WolfSheep/wolf_sheep.py
  docs/tutorials/MoneyModel.py
  mesa/agent.py
  mesa/experimental/cell_space/cell_agent.py
  mesa/experimental/devs/examples/epstein_civil_violence.py
  mesa/experimental/devs/examples/wolf_sheep.py
  mesa/model.py
  tests/test_agent.py
  tests/test_batch_run.py
  tests/test_cell_space.py
  tests/test_datacollector.py
  tests/test_lifespan.py
  tests/test_model.py
  tests/test_time.py
Labels: breaking

#2277 Update issue template to point directly at discussions
  .github/ISSUE_TEMPLATE/asking-help.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: maintenance, ignore-for-release

#2276 Readthedocs: Don't let notebook failures pass silently
  docs/conf.py
Labels: docs, ci, backport

#2282 Simplify ModelController
  mesa/visualization/solara_viz.py
Labels: enhancement

#2118 Fix deterministic behavior in `move_agent_to_one_of` with `selection="closest"`
  mesa/space.py
  tests/test_space.py
Labels: bug

#2289 Update viz tutorial to the new API
  docs/tutorials/visualization_tutorial.ipynb
Labels: docs

#2301 Fix docstring formatting
  mesa/agent.py
Labels: ignore-for-release

#2290 GroupBy: Add `count` and `agg` methods
  mesa/agent.py
  tests/test_agent.py
Labels: feature

#2302 Migration Guide: Add Model initialization requirement and automatic Agent.unique_id assignment
  docs/migration_guide.md
Labels: docs

#2305 CI: Install Mesa with uv again on Python 3.13
  .github/workflows/build_lint.yml
Labels: ci, ignore-for-release

#2300 datacollector: Allow collecting data from Agent (sub)classes
  mesa/datacollection.py
  mesa/model.py
  tests/test_datacollector.py
Labels: feature, backport-candidate

#2283 Add AgentSet.shuffle_do()
  benchmarks/BoltzmannWealth/boltzmann_wealth.py
  benchmarks/WolfSheep/wolf_sheep.py
  mesa/agent.py
  mesa/experimental/devs/examples/epstein_civil_violence.py
  mesa/experimental/devs/examples/wolf_sheep.py
  tests/test_agent.py
Labels: enhancement, backport-candidate

#2306 Deprecate Time module and all its Schedulers
  docs/migration_guide.md
  mesa/time.py
  tests/test_time.py
Labels: docs, deprecation

#2307 Update to CellCollection.select
  mesa/experimental/cell_space/cell.py
  mesa/experimental/cell_space/cell_collection.py
  tests/test_cell_space.py
Labels: enhancement

#2308 Remove schedulers from benchmark models.
  benchmarks/BoltzmannWealth/boltzmann_wealth.py
  benchmarks/Flocking/flocking.py
  benchmarks/Schelling/schelling.py
Labels: maintenance

#2310 Update version and release notes for 3.0.0a5
  HISTORY.md
Labels: ignore-for-release

#2309 Have a dedicated neighborhood property and a get_neighborhood method on Cell
  benchmarks/Schelling/schelling.py
  benchmarks/WolfSheep/wolf_sheep.py
  mesa/experimental/cell_space/cell.py
  tests/test_cell_space.py
Labels: experimental, enhancement

#2315 intro_tutorial: Don't initialize agents with an unique_id
  docs/tutorials/MoneyModel.py
  docs/tutorials/intro_tutorial.ipynb
Labels: docs

#2314 Migration guide: Intro, upgrade strategy, model.agents, headers
  docs/migration_guide.md
Labels: docs

#2313 Update version and release notes for 3.0.0a5 (part 2)
  HISTORY.md
Labels: ignore-for-release

#2317 docs: Update overview for Mesa 3.0
  docs/overview.md
Labels: docs

#2326 Migration guide: Add note about removing Agents from the model
  docs/migration_guide.md
Labels: docs, ignore-for-release

#2328 update Agent.__init__ to remove deprecation warning
  mesa/agent.py
  tests/test_agent.py
Labels: breaking

#2327 Deprecate `initialize_data_collector`
  docs/migration_guide.md
  mesa/batchrunner.py
  mesa/model.py
  tests/test_datacollector.py
Labels: backport-candidate, deprecation

#2329 tests: Resolve warnings by removing scheduler and updating arguments
  tests/test_agent.py
  tests/test_batch_run.py
  tests/test_datacollector.py
  tests/test_lifespan.py
Labels: testing

#2265 Reduce core dependencies, split in optional dependencies
  README.md
  pyproject.toml
Labels: maintenance

#2334 add super call to Model and remove self.schedule
  benchmarks/BoltzmannWealth/boltzmann_wealth.py
  mesa/model.py
  tests/test_model.py
Labels: maintenance

#2333 Move cell movement into a descriptor
  benchmarks/Schelling/schelling.py
  benchmarks/WolfSheep/wolf_sheep.py
  mesa/experimental/cell_space/cell.py
  mesa/experimental/cell_space/cell_agent.py
  tests/test_cell_space.py
Labels: feature, enhancement
