Repository projectmesa/mesa, pull requests merged in 2024-11, with the labels that each got.

#2448 Include main examples readme in docs
  .gitignore
  docs/conf.py
  docs/examples.md
  docs/examples_overview_template.txt
  mesa/examples/README.md
Labels: docs

#2447 api reorganization
  docs/apis/visualization.md
  mesa/examples/advanced/pd_grid/app.py
  mesa/examples/basic/boid_flockers/app.py
  mesa/examples/basic/boltzmann_wealth_model/app.py
  mesa/visualization/__init__.py
  mesa/visualization/components/__init__.py
  mesa/visualization/components/altair_components.py
  mesa/visualization/components/matplotlib_components.py
  mesa/visualization/mpl_space_drawing.py
  mesa/visualization/solara_viz.py
  tests/test_components_matplotlib.py
  tests/test_solara_viz.py
Labels: breaking, enhancement

#2459 Mark SolaraViz as experimental for Mesa 3.0
  docs/migration_guide.md
  docs/overview.md
  docs/tutorials/visualization_tutorial.ipynb
  mesa/visualization/__init__.py
Labels: docs, experimental

#2460 Bugfix for Solara deepcopy bug
  mesa/examples/basic/boltzmann_wealth_model/app.py
  mesa/visualization/solara_viz.py
  tests/test_solara_viz.py
Labels: bug

#2463 solaraviz kwargs related bugfix
  mesa/visualization/solara_viz.py
  tests/test_solara_viz.py
Labels: bug

#2450 Docs reorganization
  docs/apis/experimental.md
  docs/apis/visualization.md
  docs/best-practices.md
  docs/conf.py
  docs/examples_overview_template.txt
  docs/getting_started.md
  docs/index.md
  docs/packages.md
  mesa/examples/advanced/pd_grid/app.py
  mesa/visualization/__init__.py
  mesa/visualization/mpl_space_drawing.py
  mesa/visualization/solara_viz.py
  mesa/visualization/user_param.py
  tests/test_components_matplotlib.py
Labels: docs

#2466 Add release highlights for Mesa 3.0
  HISTORY.md
Labels: docs, ignore-for-release

#2468 Add support for alpha, linewidths and edgecolors to agent_portrayal
  mesa/visualization/components/matplotlib_components.py
  mesa/visualization/mpl_space_drawing.py
  tests/test_components_matplotlib.py
Labels: bug, feature

#2469 Bump version to 3.0.0, remove 2.x references
  README.md
  docs/index.md
  docs/tutorials/visualization_tutorial.ipynb
  mesa/__init__.py
Labels: maintenance

#2475 docs/tutorial: Replace scheduler in MoneyModel
  docs/tutorials/MoneyModel.py
Labels: docs

#2473 Integrate benchmarks and example models
  benchmarks/BoltzmannWealth/__init__.py
  benchmarks/BoltzmannWealth/boltzmann_wealth.py
  benchmarks/Flocking/__init__.py
  benchmarks/Flocking/flocking.py
  benchmarks/Schelling/__init__.py
  benchmarks/Schelling/schelling.py
  benchmarks/WolfSheep/__init__.py
  benchmarks/WolfSheep/wolf_sheep.py
  benchmarks/configurations.py
  benchmarks/global_benchmark.py
  mesa/examples/__init__.py
  mesa/examples/advanced/wolf_sheep/agents.py
  mesa/examples/advanced/wolf_sheep/model.py
  mesa/examples/basic/boid_flockers/agents.py
  mesa/examples/basic/boid_flockers/model.py
  mesa/examples/basic/boltzmann_wealth_model/agents.py
  mesa/examples/basic/boltzmann_wealth_model/app.py
  mesa/examples/basic/boltzmann_wealth_model/model.py
  mesa/examples/basic/boltzmann_wealth_model/st_app.py
  mesa/examples/basic/schelling/agents.py
  mesa/examples/basic/schelling/model.py
  tests/test_examples.py
Labels: example

#2478 Bugfixes to DEVS
  benchmarks/global_benchmark.py
  mesa/examples/advanced/wolf_sheep/model.py
  mesa/experimental/devs/simulator.py
  tests/test_devs.py
  tests/test_examples.py
Labels: bug, breaking, experimental

#2470 Support simulators in SolaraViz
  mesa/examples/advanced/wolf_sheep/app.py
  mesa/examples/advanced/wolf_sheep/model.py
  mesa/visualization/solara_viz.py
Labels: bug, visualisation

#2479 issue a user warning if random is None
  mesa/agent.py
  mesa/examples/advanced/pd_grid/model.py
  mesa/examples/advanced/sugarscape_g1mt/model.py
  mesa/experimental/cell_space/cell_collection.py
  mesa/experimental/cell_space/discrete_space.py
  tests/test_cell_space.py
Labels: enhancement

#2476 Remove deprecated time module
  docs/apis/time.md
  docs/mesa.md
  mesa/__init__.py
  mesa/time.py
  tests/test_import_namespace.py
  tests/test_time.py
Labels: maintenance, deprecation

#2474 Drop support for Python 3.10, require Python >= 3.11
  .github/workflows/build_lint.yml
  .pre-commit-config.yaml
  README.md
  docs/tutorials/intro_tutorial.ipynb
  mesa/__init__.py
  pyproject.toml
Labels: maintenance

#2485 examples: Add required components keyword
  mesa/examples/basic/boid_flockers/app.py
  mesa/examples/basic/virus_on_network/app.py
Labels: example, backport-candidate

#2492 examples: Fix boid_flockers viz
  mesa/examples/basic/boid_flockers/agents.py
  mesa/examples/basic/boid_flockers/app.py
Labels: example

#2487 example: Add input sliders to Sugerscape viz
  mesa/examples/advanced/sugarscape_g1mt/app.py
Labels: example, visualisation

#2489 examples/gol: Add initial fraction alive, add sliders to viz
  mesa/examples/basic/conways_game_of_life/app.py
  mesa/examples/basic/conways_game_of_life/model.py
Labels: example

#2499 Cleanup two occurances of removed scheduler
  mesa/datacollection.py
  mesa/model.py
Labels: maintenance

#2502 cell_space: Allow CellCollection to be empty
  mesa/experimental/cell_space/cell_collection.py
  tests/test_cell_space.py
Labels: bug, experimental

#2505 Only set model_parameters once
  mesa/visualization/solara_viz.py
Labels: bug, backport-candidate

#2507 remove devs related examples from devs/examples
  mesa/experimental/devs/examples/epstein_civil_violence.py
  mesa/experimental/devs/examples/wolf_sheep.py
Labels: maintenance

#2509 bugfix in global_benchmark.py
  benchmarks/global_benchmark.py
Labels: bug

#2291 Add support for Observables to MESA
  codecov.yaml
  mesa/experimental/__init__.py
  mesa/experimental/mesa_signals/__init__.py
  mesa/experimental/mesa_signals/mesa_signal.py
  mesa/experimental/mesa_signals/observable_collections.py
  mesa/experimental/mesa_signals/signals_util.py
  tests/test_mesa_signals.py
Labels: discuss, feature, experimental
