Repository projectmesa/mesa, pull requests merged in 2024-03, with the labels that each got.

#2078 Update _PropertyGrid class docstring
  mesa/space.py
Labels: docs, ignore-for-release

#2082 Add tooltip option to Altair chart
  mesa/experimental/components/altair.py
Labels: enhancement

#2038 ci: Use uv pip for faster build
  .github/workflows/build_lint.yml
  .github/workflows/release.yml
Labels: ci

#2087 docs: improve introductory tutorial
  docs/tutorials/intro_tutorial.ipynb
Labels: docs
