Repository projectmesa/mesa, pull requests merged in 2024-01, with the labels that each got.

#1948 Update version to 2.3.0-dev
  mesa/__init__.py
Labels: maintenance, ignore-for-release

#1957 Refer to just Python instead of Python 3
  README.md
  docs/index.rst
  pyproject.toml
Labels: docs

#1956 ci: Add tests for mesa-examples
  .github/workflows/build_lint.yml
Labels: testing, ci

#1955 intro tutorial: Analysing model reporters
  docs/tutorials/intro_tutorial.ipynb
Labels: docs

#1965 Make RandomActivationByType.agents_by_type backward compatible
  mesa/time.py
Labels: bug

#1943 refactor: Move Matplotlib-specific Solara components to separate file
  mesa/experimental/components/matplotlib.py
  mesa/experimental/jupyter_viz.py
  tests/test_jupyter_viz.py
Labels: maintenance

#1969 Readme: Add PyPI version button
  README.md
Labels: docs, ignore-for-release

#1968 Run release workflow on the creation of a tag
  .github/workflows/release.yml
Labels: ci, ignore-for-release

#1974 Use Python 3.12 to build Readthedocs
  .readthedocs.yml
Labels: docs, ci, ignore-for-release

#1966 Quality of Life: Make codecov less meticulous
  codecov.yaml
Labels: ci

#1979 Add performance benchmarking scripts
  .gitignore
  benchmarks/Flocking/Flocking.py
  benchmarks/Flocking/__init__.py
  benchmarks/Flocking/boid.py
  benchmarks/Schelling/Schelling.py
  benchmarks/Schelling/__init__.py
  benchmarks/WolfSheep/WolfSheep.py
  benchmarks/WolfSheep/__init__.py
  benchmarks/WolfSheep/agents.py
  benchmarks/WolfSheep/random_walk.py
  benchmarks/compare_timings.py
  benchmarks/configurations.py
  benchmarks/global_benchmark.py
  codecov.yaml
Labels: feature, Performance

#1983 Add CI workflow for performance benchmarks
  .github/workflows/benchmarks.yml
Labels: ci

#1973 Add radius argument to NetworkGrid.get_neighbors()
  mesa/space.py
  tests/test_space.py
Labels: enhancement

#1984 fix: Explicitly specify JupyterViz space view limits
  mesa/experimental/components/matplotlib.py
Labels: bug, visualisation

#1987 tests: Resolve warnings by defining PropertyLayer dtypes
  tests/test_space.py
Labels: testing

#1988 solara_viz: Add borders around ContinuousSpace
  mesa/experimental/components/matplotlib.py
Labels: experimental, visualisation

#1999 Only run benchmark bot on actual code changes
  .github/workflows/benchmarks.yml
Labels: ci, ignore-for-release

#1998 benchmarks.yml: Fix PR branch checkout when triggered by comment
  .github/workflows/benchmarks.yml
Labels: ci

#2001 benchmarks.yml: Another attempt at fixing PR branch checkout
  .github/workflows/benchmarks.yml
Labels: ci, ignore-for-release

#1942 refactor: Remove dependence on model.schedule, add clock to Model
  mesa/datacollection.py
  mesa/experimental/jupyter_viz.py
  mesa/model.py
  mesa/time.py
Labels: enhancement

#2007 Fix AgentSet inplace shuffle (and thus RandomActivation), add tests
  mesa/agent.py
  mesa/time.py
  tests/test_agent.py
  tests/test_time.py
Labels: bug, testing

#2002 benchmarks.yml: Run on addition of label instead of comment
  .github/workflows/benchmarks.yml
Labels: ci

#1972 feat: Implement Slider class for JupyterViz
  mesa/experimental/UserParam.py
  mesa/experimental/__init__.py
  mesa/experimental/jupyter_viz.py
  tests/test_jupyter_viz.py
Labels: feature, visualisation

#2010 Speedup of Agentset.shuffle
  mesa/agent.py
  tests/test_agent.py
Labels: Performance, enhancement

#2014 chore: Add Python 3.11 and 3.12 in the PyPI classifier
  pyproject.toml
Labels: maintenance, ignore-for-release

#2016 fix: Apply default value to slider
  mesa/experimental/jupyter_viz.py
Labels: bug
