Repository projectmesa/mesa, pull requests merged in 2024-10, with the labels that each got.

#2319 experimental: Integrate PropertyLayers into cell space
  mesa/experimental/cell_space/cell.py
  mesa/experimental/cell_space/discrete_space.py
  tests/test_cell_space.py
Labels: feature, experimental

#2332 viz: stop running and disable buttons when model.running is False
  mesa/visualization/solara_viz.py
Labels: enhancement

#2292 Generalize CellAgent
  benchmarks/WolfSheep/wolf_sheep.py
  mesa/experimental/cell_space/__init__.py
  mesa/experimental/cell_space/cell.py
  mesa/experimental/cell_space/cell_agent.py
  mesa/experimental/devs/examples/wolf_sheep.py
  tests/test_cell_space.py
Labels: experimental, enhancement

#2336 Visualize PropertyLayers
  mesa/visualization/components/matplotlib.py
  tests/test_solara_viz.py
Labels: feature

#2339 Update version and release notes for 3.0.0b0
  HISTORY.md
  mesa/__init__.py
Labels: ignore-for-release

#2344 use GridDraggable instead of Column in SolaraViz
  mesa/visualization/solara_viz.py
Labels: enhancement

#2325 CI: Use Python 3.13
  .github/workflows/benchmarks.yml
  .github/workflows/build_lint.yml
  .github/workflows/release.yml
Labels: ci, ignore-for-release

#2346 update legend, xlabel & format of matplotlib plots
  mesa/visualization/components/matplotlib.py
Labels: enhancement

#2340 Docs/contributing: Add section on how to create a new Release
  CONTRIBUTING.md
Labels: docs, ignore-for-release

#2350 replace model with random in AgentSet init
  mesa/agent.py
  mesa/model.py
  tests/test_agent.py
Labels: breaking, enhancement

#2357 experimental init: Fix Solara import by making it lazy
  mesa/experimental/__init__.py
Labels: bug

#2348 Add convenience properties for grid width and height
  mesa/experimental/cell_space/grid.py
Labels: enhancement

#2359 fix: pass `model.random` to schedulers
  docs/tutorials/MoneyModel.py
  mesa/time.py
Labels: bug

#2352 Add Model.rng for SPEC-7 compliant numpy random number generation
  mesa/model.py
  tests/test_model.py
Labels: feature

#2374 __init__.py: Import mesa.experimental
  mesa/__init__.py
Labels: enhancement

#2375 Complete docstring in `Model.reset_rng`
  mesa/model.py
Labels: ignore-for-release

#2368 fix: register agent after creating unique_id and pos attributes
  mesa/agent.py
Labels: bug

#2369 Release notes: Add example category
  .github/release.yml
Labels: maintenance

#2378 Bugfix for deepcopy / pickling discrete spaces
  mesa/experimental/cell_space/cell.py
  mesa/experimental/cell_space/discrete_space.py
  mesa/experimental/cell_space/network.py
  tests/test_cell_space.py
Labels: bug, experimental

#2347 Update migration_guide.md
  docs/migration_guide.md
Labels: docs

#2384 Improve Mesa 3.0 beta 1 release notes
  HISTORY.md
Labels: ignore-for-release

#2390 Explicitly test basic examples
  mesa/examples/basic/boltzmann_wealth_model/model.py
  mesa/examples/basic/conways_game_of_life/model.py
  mesa/examples/basic/virus_on_network/model.py
  tests/test_examples.py
Labels: testing, example

#2392 Include examples in readthedocs (port)
  .gitignore
  docs/README.md
  docs/apis/experimental.md
  docs/conf.py
  docs/example_template.txt
  docs/examples.md
  docs/examples_overview_template.txt
  docs/index.md
  docs/overview.md
  docs/packages.md
  mesa/examples/basic/conways_game_of_life/agents.py
  mesa/examples/basic/conways_game_of_life/app.py
  mesa/examples/basic/conways_game_of_life/requirements.txt
  mesa/examples/basic/conways_game_of_life/server.py
  mesa/examples/basic/schelling/Readme.md
  mesa/examples/basic/virus_on_network/Readme.md
Labels: docs

#2394 remove_agents method added to model
  mesa/agent.py
  mesa/model.py
  tests/test_model.py
Labels: feature

#2398 Fix for mistaken removal of _draw_grid
  mesa/visualization/components/matplotlib.py
Labels: bug

#2399 fixes weakref bug in shuffe_do
  mesa/agent.py
  tests/test_agent.py
Labels: bug

#2400 Pass through model.rgn in agent analogous to model.random
  mesa/agent.py
  tests/test_agent.py
Labels: feature

#2409 Add empty `pull_request_template.md` to enable PR template chooser
  .github/pull_request_template.md
Labels: maintenance

#2406 Update Schelling Readme.md
  mesa/examples/basic/schelling/Readme.md
Labels: docs

#2403 Update Conway example
  mesa/examples/basic/conways_game_of_life/Readme.md
  mesa/examples/basic/conways_game_of_life/app.py
  mesa/examples/basic/conways_game_of_life/portrayal.py
  mesa/examples/basic/conways_game_of_life/st_app.py
Labels: docs

#2405 Boltzman readme
  mesa/examples/basic/boltzmann_wealth_model/Readme.md
Labels: docs

#2404 Update Readme.md of Boid flockers
  mesa/examples/basic/boid_flockers/Readme.md
Labels: docs

#2411 update_tutorial environment
  .virtual_documents/docs/tutorials/intro_tutorial.ipynb
  .virtual_documents/docs/tutorials/visualization_tutorial.ipynb
  binder/environment.yml
  docs/tutorials/intro_tutorial.ipynb
  docs/tutorials/visualization_tutorial.ipynb
Labels: enhancement

#2414 reactivate ruff for advanced examples and include them in tests
  mesa/examples/__init__.py
  mesa/examples/advanced/pd_grid/app.py
  mesa/examples/advanced/sugarscape_g1mt/agents.py
  mesa/examples/advanced/sugarscape_g1mt/app.py
  mesa/examples/advanced/sugarscape_g1mt/model.py
  mesa/examples/advanced/sugarscape_g1mt/tests.py
  mesa/examples/advanced/wolf_sheep/app.py
  mesa/examples/advanced/wolf_sheep/model.py
  pyproject.toml
  tests/test_examples.py
Labels: testing, example

#2420 space: Add note that Grids are maintenance only
  mesa/space.py
Labels: docs

#2419 Migration guide: Update automatic unique_id assignment examples
  docs/migration_guide.md
Labels: docs

#2418 add agents property to all spaces
  mesa/experimental/cell_space/discrete_space.py
  mesa/space.py
  tests/test_cell_space.py
  tests/test_space.py
Labels: feature

#2425 Remove duplicate ."virtual_documents"
  .virtual_documents/docs/tutorials/intro_tutorial.ipynb
  .virtual_documents/docs/tutorials/visualization_tutorial.ipynb
Labels: ignore-for-release

#2424 best-practices: Update Model Layout section
  docs/best-practices.md
Labels: docs

#2422 docs: Clean-up index.md
  docs/images/Mesa_Screenshot.png
  docs/images/wolf_scheep.png
  docs/index.md
Labels: docs

#2426 Update version and release notes for 3.0.0b2
  HISTORY.md
  mesa/__init__.py
Labels: ignore-for-release

#2429 Updates to Epstein example
  mesa/examples/advanced/epstein_civil_violence/agents.py
  mesa/examples/advanced/epstein_civil_violence/app.py
  mesa/examples/advanced/epstein_civil_violence/model.py
Labels: example

#2430 Matplotlib refactor
  docs/apis/visualization.md
  docs/migration_guide.md
  docs/overview.md
  docs/tutorials/visualization_tutorial.ipynb
  mesa/examples/advanced/epstein_civil_violence/app.py
  mesa/examples/advanced/pd_grid/app.py
  mesa/examples/advanced/sugarscape_g1mt/app.py
  mesa/examples/advanced/wolf_sheep/app.py
  mesa/examples/basic/boid_flockers/app.py
  mesa/examples/basic/boltzmann_wealth_model/app.py
  mesa/examples/basic/conways_game_of_life/app.py
  mesa/examples/basic/schelling/app.py
  mesa/examples/basic/virus_on_network/app.py
  mesa/visualization/__init__.py
  mesa/visualization/components/matplotlib.py
  tests/test_components_matplotlib.py
  tests/test_solara_viz.py
Labels: feature, enhancement, visualisation

#2441 remove deprecated HexGrid class
  mesa/space.py
Labels: maintenance

#2444 Update wolf-sheep png and fix typo in file name
  docs/images/wolf_scheep.png
  docs/images/wolf_sheep.png
  docs/index.md
Labels: docs

#2442 Update examples to use updated space drawing
  mesa/examples/advanced/epstein_civil_violence/app.py
  mesa/examples/advanced/pd_grid/app.py
  mesa/examples/advanced/sugarscape_g1mt/app.py
  mesa/examples/basic/conways_game_of_life/app.py
  mesa/examples/basic/schelling/app.py
  mesa/examples/basic/virus_on_network/app.py
Labels: example

#2445 expand ax.scatter kwargs that can be used
  docs/overview.md
  mesa/examples/basic/boltzmann_wealth_model/app.py
  mesa/visualization/components/matplotlib.py
Labels: enhancement
