Repository projectmesa/mesa, pull requests merged in 2024-07, with the labels that each got.

#2091 Remove mesa.flat namespace
  mesa/flat/__init__.py
  mesa/flat/visualization.py
  tests/test_import_namespace.py
Labels: breaking

#2161 Fix pre-commit issues: Codespels and typecheck
  .codespellignore
  CODE_OF_CONDUCT.md
  docs/tutorials/adv_tutorial_legacy.ipynb
  mesa/visualization/UserParam.py
Labels: ignore-for-release

#2133 breaking: Remove visualization_old (mesa-viz-tornado)
  docs/index.md
  docs/mesa.md
  docs/mesa.visualization_old.md
  docs/mesa.visualization_old.modules.md
  docs/modular-visualization.md
  docs/overview.md
  docs/tutorials/adv_tutorial_legacy.ipynb
  docs/tutorials/intro_tutorial.ipynb
  mesa/__init__.py
  mesa/cookiecutter-mesa/{{cookiecutter.snake}}/app.pytemplate
  mesa/cookiecutter-mesa/{{cookiecutter.snake}}/run.pytemplate
  mesa/cookiecutter-mesa/{{cookiecutter.snake}}/{{cookiecutter.snake}}/model.pytemplate
  mesa/cookiecutter-mesa/{{cookiecutter.snake}}/{{cookiecutter.snake}}/server.pytemplate
  pyproject.toml
  tests/test_import_namespace.py
  tests/test_tornado.py
  tests/test_usersettableparam.py
  tests/test_visualization.py
Labels: breaking

#2162 Update visualisation docs
  docs/apis/visualization.md
  mesa/visualization/jupyter_viz.py
Labels: docs

#2165 Jupyter Viz: Don't avoid interactive backend
  mesa/visualization/jupyter_viz.py
Labels: bug

#2169 Remove last remnants of visualization_old
  mesa/visualization_old/ModularVisualization.py
  mesa/visualization_old/TextVisualization.py
  mesa/visualization_old/UserParam.py
  mesa/visualization_old/__init__.py
  mesa/visualization_old/modules.py
  tests/test_main.py
Labels: maintenance, ignore-for-release

#2167 Set version to 3.0.0a0 and update release notes
  HISTORY.md
  mesa/__init__.py
Labels: maintenance, ignore-for-release

#2172 Add .venv/ to .gitignore
  .gitignore
Labels: maintenance, ignore-for-release

#2160 Add original conference paper link to docs
  docs/index.md
Labels: docs

#2174 Update .readthedocs.yaml: Use latest Ubuntu and Python versions
  .readthedocs.yml
Labels: maintenance, ignore-for-release

#2180 viz: Combine code for rendering in browser and Jupyter
  mesa/visualization/jupyter_viz.py
Labels: breaking, visualisation

#2183 fix: Use model.schedule.steps -> mode._steps for batch_run
  mesa/batchrunner.py
Labels: bug
