Repository projectmesa/mesa, pull requests merged in 2025-05, with the labels that each got.

#2764 Benchmarks documentation
  benchmarks/README.md
Labels: docs

#2761 Add `.coderabbit.yaml` file to allow reviewing and updating our CodeRabbit configuration
  .coderabbit.yaml
Labels: maintenance

#2780 Bugfix ModelCreator for required model parameters and user adjusted model parameters
  mesa/visualization/solara_viz.py
  tests/test_solara_viz.py
Labels: visualisation

#2788 docs/nix flake
  docs/index.md
Labels: feature

#2786 Added `AgentPortrayalStyle` and `PropertyLayerStyle`
  mesa/examples/advanced/sugarscape_g1mt/app.py
  mesa/examples/advanced/sugarscape_g1mt/tests.py
  mesa/visualization/components/__init__.py
  mesa/visualization/components/portrayal_components.py
  mesa/visualization/mpl_space_drawing.py
  tests/test_portrayal_components.py
Labels: visualisation
