Repository projectmesa/mesa, pull requests merged in 2025-01, with the labels that each got.

#2554 Small draw_space docstring fix
  mesa/visualization/mpl_space_drawing.py
Labels: docs

#2553 Update pd_grid example analysis.ipynb
  mesa/examples/advanced/pd_grid/analysis.ipynb
Labels: bug

#2593 examples/pd_grid: Clear outputs of analysis notebook
  mesa/examples/advanced/pd_grid/analysis.ipynb
Labels: maintenance, ignore-for-release

#2594 Update release notes and version for 3.1.2
  HISTORY.md
  mesa/__init__.py
Labels: ignore-for-release

#2595 Contributing: Add link to video of release process
  CONTRIBUTING.md
Labels: ignore-for-release

#2598 Bugfix for non deterministic rng behavior
  mesa/model.py
  tests/test_model.py
Labels: bug

#2584 Reimplementation of Continuous Space
  benchmarks/configurations.py
  mesa/examples/basic/boid_flockers/agents.py
  mesa/examples/basic/boid_flockers/app.py
  mesa/examples/basic/boid_flockers/model.py
  mesa/experimental/__init__.py
  mesa/experimental/continuous_space/__init__.py
  mesa/experimental/continuous_space/continuous_space.py
  mesa/experimental/continuous_space/continuous_space_agents.py
  mesa/visualization/mpl_space_drawing.py
  pyproject.toml
  tests/test_continuous_space.py
Labels: feature, experimental

#2596 Add render interval slider to control visualization update frequency
  mesa/visualization/solara_viz.py
Labels: enhancement, visualisation

#2613 add docs for continuous space
  docs/apis/experimental.md
Labels: docs, ignore-for-release

#2612 Update release notes and version for 3.1.3
  HISTORY.md
  mesa/__init__.py
Labels: ignore-for-release

#2617 remove remnants of mesa cli
  docs/getting_started.md
  pyproject.toml
Labels: maintenance

#2618 remove any reference to using --pre
  README.md
  docs/index.md
  docs/tutorials/intro_tutorial.ipynb
Labels: docs

#2633 benchmarks.yml: Install SciPy and use uv for pip install
  .github/workflows/benchmarks.yml
Labels: ci

#2639 bugfix for draw_property_layer
  mesa/visualization/mpl_space_drawing.py
Labels: bug, visualisation

#2609 Fixed hex-space draw function to avoid overlaps
  mesa/visualization/mpl_space_drawing.py
Labels: enhancement, visualisation

#2651 Uses array for hex grid property layer fix
  mesa/visualization/mpl_space_drawing.py
Labels: bug
