Repository projectmesa/mesa, pull requests merged in 2025-04, with the labels that each got.

#2747 Debug option for errors in visualisation
  mesa/visualization/solara_viz.py
Labels: visualisation

#2731 update intro tutorial discrete space
  docs/getting_started.md
  docs/images/Discrete_Space.drawio.png
  docs/index.md
  docs/overview.md
  docs/tutorials/0_first_model.ipynb
  docs/tutorials/1_adding_space.ipynb
  docs/tutorials/2_collecting_data.ipynb
  docs/tutorials/3_agentset.ipynb
  docs/tutorials/4_visualization_basic.ipynb
  docs/tutorials/5_visualization_dynamic_agents.ipynb
  docs/tutorials/6_visualization_custom.ipynb
  docs/tutorials/7_batch_run.ipynb
  docs/tutorials/8_comparing_scenarios.ipynb
  docs/tutorials/intro_tutorial.ipynb
  docs/tutorials/visualization_tutorial.ipynb
  mesa/discrete_space/property_layer.py
Labels: docs

#2753 Debug option for errors in visualisation front end
  mesa/visualization/solara_viz.py
Labels: enhancement, visualisation

#2755 Add support for dynamic discrete spaces
  mesa/discrete_space/cell.py
  mesa/discrete_space/discrete_space.py
  mesa/discrete_space/network.py
  tests/test_discrete_space.py
Labels: enhancement, trigger-benchmarks

#2743 Support multiple functions in AgentSet `agg` method
  mesa/agent.py
  tests/test_agent.py
Labels: enhancement

#2748 Meta agents
  docs/apis/experimental.md
  mesa/agent.py
  mesa/examples/__init__.py
  mesa/examples/advanced/alliance_formation/Readme.md
  mesa/examples/advanced/alliance_formation/__init__ .py
  mesa/examples/advanced/alliance_formation/agents.py
  mesa/examples/advanced/alliance_formation/app.py
  mesa/examples/advanced/alliance_formation/model.py
  mesa/experimental/__init__.py
  mesa/experimental/meta_agents/__init__.py
  mesa/experimental/meta_agents/meta_agent.py
  mesa/model.py
  tests/test_examples.py
  tests/test_meta_agents.py
  tests/test_solara_viz.py
Labels: feature, example, experimental
